### ISSUE TITLE
作者的语言切换功能

### ISSUE THREAD

**Issue by coraing** [flftfqwxf/mockserver#12]
## DESC
在找postman时找到你的作品，发现语言切换功能能6，想请教一下是怎么实现的

## ENV

Platform:

Node.js Version:

mockserver Version:

**Comment by flftfqwxf** [comment]
@coraing 自己写的语言包，在后台配置使用不同的语言，根据header头信息来判断默认语言，通过COOKIE记录手动选择语言，另外翻译很烂，如果英语好，可以帮忙翻译一下

> /src/common/config/locale/

 
目录下为语言包
