### ISSUE TITLE
同一接口不同协议不能添加

### ISSUE THREAD

**Issue by buxuku** [flftfqwxf/mockserver#14]
比如我有两个接口，一个是 POST abc.com/a

一个是GET abc.com/a

这种情况下是无法添加接口的。

**Comment by flftfqwxf** [comment]
@buxuku 经测试是可以添加的，在线上的DEMO上，也是可以添加的，建议你可以更新到新版本再试试

**Comment by buxuku** [comment]
已经可以添加，非常感谢。
