### ISSUE TITLE
关于URL正则匹配的一点疑问

### ISSUE THREAD

**Issue by buxuku** [flftfqwxf/mockserver#15]
现在我有两个接口：

A : `/api/a?` 匹配模式为只匹配？前面部分

B: `/api/abc?` 匹配模式为只匹配？前面部分

这个时候我只访问`/api/a?`是正常的，但如果访问`/api/a?page=1`,则会提示`有多个接口使用了此路径`

我再增加一个接口

C: `/api/a/:id` 匹配模式为精确匹配，并删除接口B，再访问`/api/a?page=1`,则会提示`获取数据错误,可能是接口不存在,或参数错误,错误信息`

我已经在线上DEOM上添加了类似接口，烦请作者可以测试一下。

另本地在类似场景下得到的SQL结果如下

![1](https://user-images.githubusercontent.com/7866330/29108990-dae236ba-7d13-11e7-8a63-3f805099c6c3.jpg)

**Comment by flftfqwxf** [comment]
@buxuku 好,我抽空查看一下

**Comment by flftfqwxf** [comment]
此问题已解决
