### ISSUE TITLE
感觉跑起来比较难...

### ISSUE THREAD

**Issue by wslx520** [flftfqwxf/mockserver#16]
## DESC

门槛较高.要安装mysql

且需要跨域访问时,还得自己配nginx

我期望像json-server那样使用简单的mock服务器,但json-server太简单了,少了很多配置.

还有就是对于mock服务器来说,跨域访问是基本需求,我期望在这方面不要搞的太复杂.nodejs自身实现跨域访问和代理都不算难, http-proxy-middleware, hapi的h2o2, json-server都实现过.

抱歉我并没有尝试跑一下这个项目,主要是感觉使用方式和其他的很不一样,所以打了退堂鼓.如果有什么我说错了的,期望不要介意.

## ENV

Platform:

Node.js Version:

mockserver Version:

**Comment by flftfqwxf** [comment]
@wslx520 本身就支持跨域访问啊，你文档都没看清楚

**Comment by wslx520** [comment]
@flftfqwxf 好的
