### ISSUE TITLE
请求的参数进行校验

### ISSUE THREAD

**Issue by zz-fe** [flftfqwxf/mockserver#18]
## DESC

提一个需求吧 

希望客户端在请求数据的时候   mock返回数据之前 要与数据库中BODY进行参数对比

## ENV

Platform:

Node.js Version:

mockserver Version:

**Comment by fambit025** [comment]
如果没有这个功能，感觉应用起来会有比较大的局限性，还是请多多完善哦。

**Comment by fambit025** [comment]
哦，那请问一下，您这边知道有那种参数校验的project可以是实现么？最好是有一个类似这个的web界面，可以方便配置的。感谢感谢

**Comment by flftfqwxf** [comment]
@fambit025 没有，另外你需要校验参数的具体需求和场景是什么？
