### ISSUE TITLE
Cannot find module 'mixin'

### ISSUE THREAD

**Issue by panw3i** [flftfqwxf/mockserver#22]
## ENV

Platform:

Node.js Version:

mockserver Version:

**Comment by flftfqwxf** [comment]
@panw3i 请先确认是不是本地安装包出现问题，请详细说明

**Comment by yaozhixing** [comment]
我也出现同样的问题
按照文档说明，安装一切良好，配置本地数据库的时候，结果报错误了。
Internal Server Error
Cannot find module 'mixin'

**Comment by flftfqwxf** [comment]
@yaozhixing 确实有包没有写入配置中，已经解决
