### ISSUE TITLE
请问作者这个要怎么配置才能访问到

### ISSUE THREAD

**Issue by guanbiao33** [flftfqwxf/mockserver#23]
添加了接口
但是我在react里面
let data =await axios.post('http://127.0.0.1:8033/ff30d02a10c33f09e86b/api/user/login',{
      params:{
        account:this.state.account,
        password:this.state.password
      }
    }).then(data=>{
      return data;
    });
返回提示{code: "ETIMEDOUT", errno: "ETIMEDOUT", syscall: "connect", address: "47.93.62.181", port: 8034}
address
:
"47.93.62.181"
code
:
"ETIMEDOUT"
errno
:
"ETIMEDOUT"
port
:
8034
syscall
:
"connect"
errorMessage
:
"Get data is failed,API dose not exist or parameters are error,may be you should send some parameters to proxy URL"
proxyUrl
:
"http://47.93.62.181:8034//api/user/login"
我关闭了二次代理的啊

**Comment by flftfqwxf** [comment]
@guanbiao33 未复现你说的问题，请说明版本，另确认你选择的请求类型，和二次代码状态，可以在列表中点击接口进入postman页面查看返回数据情况
