### ISSUE TITLE
docker环境下无法连接数据库的问题

### ISSUE THREAD

**Issue by passioncsu** [flftfqwxf/mockserver#25]
## DESC
docker环境下当访问数据库的时候不管怎么填地址,都提示
```
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'172.21.0.3' (using password: YES)
```
之类的错误,网上说node-mysql的版本问题. 可是我换有些电脑又可以,玄,留个issues,期待后续人员解决, 感谢作者的无私贡献,项目正是我想要的

**Comment by flftfqwxf** [comment]
这个应该是你docker的权限设置没对吧
