### ISSUE TITLE
这个遮罩层怎么实现的？

### ISSUE THREAD

**Issue by cunchao** [flftfqwxf/mockserver#27]
## DESC

添加接口的loading遮罩层没找到在哪里实现的，可否告知，另外项目不升级到thinkjs3吗，和v2差别挺大，一些方法都废除了！

## ENV

Platform:

Node.js Version:

mockserver Version:

**Comment by flftfqwxf** [comment]
你在代码里搜一下load或loading应该能找到，暂时不会升级thinkjs
