### ISSUE TITLE
响应数据参数说明不能进行保存

### ISSUE THREAD

**Issue by wuzhendev** [flftfqwxf/mockserver#7]
@flftfqwxf 你好，响应参数设置中的”响应数据参数说明“部分不能进行保存，每次进入修改API后都会还原成默认值，使用的是2.1.5版本，麻烦您进行下修改

**Comment by flftfqwxf** [comment]
@wuzhendev 我看一下

**Comment by flftfqwxf** [comment]
@wuzhendev  已经改了，fork最新代码
